services:
  - type: web
    name: chess-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 